#!/bin/bash

# See READMe for more details

desktop=$(printenv XDG_SESSION_DESKTOP)
if [ "$desktop" == "openbox" ]
    then
        obsession-logout
    elif [ "$desktop" == "xfce" ]
        then
            xfce4-session-logout
    else
        echo "Desktopumgebung nicht unterstützt. Beende."
        exit 1
fi
